# Generated by Django 5.0 on 2023-12-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
