# Generated by Django 5.0 on 2023-12-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='state',
            new_name='status',
        ),
    ]
